-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Carrito"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cantidad integer NOT NULL,
    "idUsuario_id" integer NOT NULL,
    "idOrder_id" bigint,
    CONSTRAINT "Carrito_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Comuna"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    region_id integer NOT NULL,
    "codigoPostal" character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT "Comuna_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."DireccionEnvio"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    calle character varying(100) COLLATE pg_catalog."default" NOT NULL,
    numero integer NOT NULL,
    comuna character varying(100) COLLATE pg_catalog."default" NOT NULL,
    region character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "idUsuario_id" integer NOT NULL,
    estado character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "DireccionEnvio_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."OrderItem"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cantidad integer NOT NULL,
    "idUsuario_id" integer NOT NULL,
    order_id bigint,
    "idProducto_id" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    costo_compra integer,
    fecha_inicio date,
    fecha_termino date,
    CONSTRAINT "OrderItem_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Producto"
(
    marca character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precio integer NOT NULL,
    oferta boolean NOT NULL,
    "precioAnterior" integer NOT NULL,
    descuento integer,
    "VIN" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    patente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    "tipoEnvio" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "costoEnvio" integer NOT NULL,
    total integer NOT NULL,
    comuna_id integer,
    vendedor_id integer NOT NULL,
    region_id integer,
    CONSTRAINT "Producto_pkey" PRIMARY KEY ("VIN")
);

CREATE TABLE IF NOT EXISTS public."ProductoImagen"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    imagen character varying(100) COLLATE pg_catalog."default" NOT NULL,
    producto_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "ProductoImagen_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Region"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Region_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    comuna character varying(100) COLLATE pg_catalog."default" NOT NULL,
    region character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    CONSTRAINT "User_pkey" PRIMARY KEY (id),
    CONSTRAINT "User_user_id_key" UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.home_arriendo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    costo double precision NOT NULL,
    producto_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT home_arriendo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_direccion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    direccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    perfil_id bigint NOT NULL,
    CONSTRAINT home_direccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_disponibilidad
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_termino timestamp with time zone NOT NULL,
    "Producto_id" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT home_disponibilidad_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_empresa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    perfil_id bigint NOT NULL,
    "comunaEmpresa" character varying(100) COLLATE pg_catalog."default",
    "emailEmpresa" character varying(100) COLLATE pg_catalog."default",
    "rutEmpresa" character varying(10) COLLATE pg_catalog."default",
    "telefonoEmpresa" character varying(100) COLLATE pg_catalog."default",
    "regionEmpresa" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT home_empresa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_home
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    url character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT home_home_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_loginform
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    checkbox boolean NOT NULL,
    CONSTRAINT home_loginform_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_modificarproductofrom
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Nombre" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Precio" integer NOT NULL,
    "Oferta" boolean NOT NULL,
    "PrecioAnterior" integer NOT NULL,
    "Descuento" integer,
    "tipoEnvio" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "costoEnvio" double precision NOT NULL,
    "Descripcion" text COLLATE pg_catalog."default" NOT NULL,
    region character varying(100) COLLATE pg_catalog."default" NOT NULL,
    comuna character varying(100) COLLATE pg_catalog."default" NOT NULL,
    imagen character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT home_modificarproductofrom_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_order
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_ordered timestamp with time zone NOT NULL,
    "pagoProcesado" boolean NOT NULL,
    "enPreparacion" boolean NOT NULL,
    "enRetiro" boolean NOT NULL,
    retirado boolean NOT NULL,
    complete boolean NOT NULL,
    transaction_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DireccionEnvio_id" integer,
    cliente_id integer,
    boleta_generada boolean,
    CONSTRAINT home_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_perfil
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rut character varying(10) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT home_perfil_pkey PRIMARY KEY (id),
    CONSTRAINT home_perfil_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.home_transaccion
(
    id bigserial NOT NULL,
    monto integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    orden_id bigint NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT home_transaccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.social_auth_association
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    server_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    handle character varying(255) COLLATE pg_catalog."default" NOT NULL,
    secret character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issued integer NOT NULL,
    lifetime integer NOT NULL,
    assoc_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT social_auth_association_pkey PRIMARY KEY (id),
    CONSTRAINT social_auth_association_server_url_handle_078befa2_uniq UNIQUE (server_url, handle)
);

CREATE TABLE IF NOT EXISTS public.social_auth_code
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    verified boolean NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT social_auth_code_pkey PRIMARY KEY (id),
    CONSTRAINT social_auth_code_email_code_801b2d02_uniq UNIQUE (email, code)
);

CREATE TABLE IF NOT EXISTS public.social_auth_nonce
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    server_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" integer NOT NULL,
    salt character varying(65) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT social_auth_nonce_pkey PRIMARY KEY (id),
    CONSTRAINT social_auth_nonce_server_url_timestamp_salt_f6284463_uniq UNIQUE (server_url, "timestamp", salt)
);

CREATE TABLE IF NOT EXISTS public.social_auth_partial
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    token character varying(32) COLLATE pg_catalog."default" NOT NULL,
    next_step smallint NOT NULL,
    backend character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    data jsonb NOT NULL,
    CONSTRAINT social_auth_partial_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.social_auth_usersocialauth
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    provider character varying(32) COLLATE pg_catalog."default" NOT NULL,
    uid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    CONSTRAINT social_auth_usersocialauth_pkey PRIMARY KEY (id),
    CONSTRAINT social_auth_usersocialauth_provider_uid_e6b5e668_uniq UNIQUE (provider, uid)
);

ALTER TABLE IF EXISTS public."Carrito"
    ADD CONSTRAINT "Carrito_idOrder_id_49cc8e13_fk_home_order_id" FOREIGN KEY ("idOrder_id")
    REFERENCES public.home_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Carrito_idOrder_id_49cc8e13"
    ON public."Carrito"("idOrder_id");


ALTER TABLE IF EXISTS public."Carrito"
    ADD CONSTRAINT "Carrito_idUsuario_id_7abc8ba4_fk_auth_user_id" FOREIGN KEY ("idUsuario_id")
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Carrito_idUsuario_id_7abc8ba4"
    ON public."Carrito"("idUsuario_id");


ALTER TABLE IF EXISTS public."Comuna"
    ADD CONSTRAINT "Comuna_region_id_d0630bb2_fk_Region_id" FOREIGN KEY (region_id)
    REFERENCES public."Region" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Comuna_region_id_d0630bb2"
    ON public."Comuna"(region_id);


ALTER TABLE IF EXISTS public."DireccionEnvio"
    ADD CONSTRAINT "DireccionEnvio_idUsuario_id_a8897c0e_fk_auth_user_id" FOREIGN KEY ("idUsuario_id")
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "DireccionEnvio_idUsuario_id_a8897c0e"
    ON public."DireccionEnvio"("idUsuario_id");


ALTER TABLE IF EXISTS public."OrderItem"
    ADD CONSTRAINT "OrderItem_idProducto_id_730dbb57_fk_Producto_VIN" FOREIGN KEY ("idProducto_id")
    REFERENCES public."Producto" ("VIN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "OrderItem_idProducto_id_730dbb57_like"
    ON public."OrderItem"("idProducto_id");


ALTER TABLE IF EXISTS public."OrderItem"
    ADD CONSTRAINT "OrderItem_idUsuario_id_4ebdd1a6_fk_auth_user_id" FOREIGN KEY ("idUsuario_id")
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "OrderItem_idUsuario_id_4ebdd1a6"
    ON public."OrderItem"("idUsuario_id");


ALTER TABLE IF EXISTS public."OrderItem"
    ADD CONSTRAINT "OrderItem_order_id_d1e3f0fb_fk_home_order_id" FOREIGN KEY (order_id)
    REFERENCES public.home_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "OrderItem_order_id_d1e3f0fb"
    ON public."OrderItem"(order_id);


ALTER TABLE IF EXISTS public."Producto"
    ADD CONSTRAINT "Producto_comuna_id_dd0d50dd_fk_Comuna_id" FOREIGN KEY (comuna_id)
    REFERENCES public."Comuna" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Producto_comuna_id_dd0d50dd"
    ON public."Producto"(comuna_id);


ALTER TABLE IF EXISTS public."Producto"
    ADD CONSTRAINT "Producto_region_id_e231a1f7_fk_Region_id" FOREIGN KEY (region_id)
    REFERENCES public."Region" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Producto_region_id_e231a1f7"
    ON public."Producto"(region_id);


ALTER TABLE IF EXISTS public."Producto"
    ADD CONSTRAINT "Producto_vendedor_id_f7f04243_fk_auth_user_id" FOREIGN KEY (vendedor_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Producto_vendedor_id_f7f04243"
    ON public."Producto"(vendedor_id);


ALTER TABLE IF EXISTS public."ProductoImagen"
    ADD CONSTRAINT "ProductoImagen_producto_id_07a559a3_fk_Producto_VIN" FOREIGN KEY (producto_id)
    REFERENCES public."Producto" ("VIN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ProductoImagen_producto_id_07a559a3"
    ON public."ProductoImagen"(producto_id);


ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT "User_user_id_6c4153d4_fk_auth_user_id" FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "User_user_id_key"
    ON public."User"(user_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.home_arriendo
    ADD CONSTRAINT "home_arriendo_producto_id_381e3397_fk_Producto_VIN" FOREIGN KEY (producto_id)
    REFERENCES public."Producto" ("VIN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_arriendo_producto_id_381e3397_like
    ON public.home_arriendo(producto_id);


ALTER TABLE IF EXISTS public.home_arriendo
    ADD CONSTRAINT home_arriendo_usuario_id_9957b65d_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_arriendo_usuario_id_9957b65d
    ON public.home_arriendo(usuario_id);


ALTER TABLE IF EXISTS public.home_direccion
    ADD CONSTRAINT home_direccion_perfil_id_0402a1da_fk_home_perfil_id FOREIGN KEY (perfil_id)
    REFERENCES public.home_perfil (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_direccion_perfil_id_0402a1da
    ON public.home_direccion(perfil_id);


ALTER TABLE IF EXISTS public.home_disponibilidad
    ADD CONSTRAINT "home_disponibilidad_Producto_id_4a53a538_fk_Producto_VIN" FOREIGN KEY ("Producto_id")
    REFERENCES public."Producto" ("VIN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "home_disponibilidad_Producto_id_4a53a538_like"
    ON public.home_disponibilidad("Producto_id");


ALTER TABLE IF EXISTS public.home_empresa
    ADD CONSTRAINT home_empresa_perfil_id_0c5ccda6_fk_home_perfil_id FOREIGN KEY (perfil_id)
    REFERENCES public.home_perfil (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_empresa_perfil_id_0c5ccda6
    ON public.home_empresa(perfil_id);


ALTER TABLE IF EXISTS public.home_order
    ADD CONSTRAINT "home_order_DireccionEnvio_id_ddbc4152_fk_DireccionEnvio_id" FOREIGN KEY ("DireccionEnvio_id")
    REFERENCES public."DireccionEnvio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "home_order_DireccionEnvio_id_ddbc4152"
    ON public.home_order("DireccionEnvio_id");


ALTER TABLE IF EXISTS public.home_order
    ADD CONSTRAINT home_order_cliente_id_2b51a010_fk_auth_user_id FOREIGN KEY (cliente_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_order_cliente_id_2b51a010
    ON public.home_order(cliente_id);


ALTER TABLE IF EXISTS public.home_perfil
    ADD CONSTRAINT home_perfil_user_id_046b9c19_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_perfil_user_id_key
    ON public.home_perfil(user_id);


ALTER TABLE IF EXISTS public.home_transaccion
    ADD CONSTRAINT home_transaccion_orden_id_f2251a7e_fk_home_order_id FOREIGN KEY (orden_id)
    REFERENCES public.home_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_transaccion_orden_id_f2251a7e
    ON public.home_transaccion(orden_id);


ALTER TABLE IF EXISTS public.home_transaccion
    ADD CONSTRAINT home_transaccion_usuario_id_249baf7b_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_transaccion_usuario_id_249baf7b
    ON public.home_transaccion(usuario_id);


ALTER TABLE IF EXISTS public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS social_auth_usersocialauth_user_id_17d28448
    ON public.social_auth_usersocialauth(user_id);

END;